# Generated by Django 4.2.2 on 2023-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0006_alter_guitar_discount_alter_guitar_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
