# Generated by Django 4.2.2 on 2023-09-28 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0007_alter_guitar_discount'),
    ]

    operations = [
    ]
