# Generated by Django 4.2.2 on 2023-09-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0008_auto_20230928_1610'),
    ]

    operations = [
    ]
