# Generated by Django 4.2.2 on 2023-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0009_auto_20230928_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
