# Generated by Django 4.2.2 on 2023-09-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0010_alter_guitar_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='discount',
        ),
    ]
