# Generated by Django 4.2.2 on 2023-09-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0012_alter_guitar_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='Amp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrument.amp'),
        ),
        migrations.AddField(
            model_name='guitar',
            name='ElectricGuitar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instrument.electricguitar'),
        ),
    ]
