# Generated by Django 4.2.2 on 2023-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0013_guitar_amp_guitar_electricguitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
