# Generated by Django 4.2.2 on 2023-09-28 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0014_guitar_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guitar',
            name='discount',
        ),
    ]
